/*
(C) Copyright 2015 Nuxeo SA (http://nuxeo.com/) and contributors.

All rights reserved. This program and the accompanying materials
are made available under the terms of the GNU Lesser General Public License
(LGPL) version 2.1 which accompanies this distribution, and is available at
http://www.gnu.org/licenses/lgpl.html

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

Contributors:
  Josh Fletcher <jfletcher@nuxeo.com>
*/
var mimeTypes = {
  findByMimeType: function (mimeType) {
    for (var i = 0; i < this.mimeTypes.length; i++) {
      if (this.mimeTypes[i].mimeType === mimeType) {
        return this.mimeTypes[i];
      }
    }
    // Not found.
    return null;
  },

  // Mainly From:
  // http://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?view=markup
  // https://developers.google.com/drive/web/mime-types
  mimeTypes: [
    {
      "mimeType": "application/x-gzip",
      "fileExtensions": ".gz",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-tar",
      "fileExtensions": ".tar,.tgz",
      "friendlyName": ""
    }, {
      "mimeType": "application/andrew-inset",
      "fileExtensions": ".ez",
      "friendlyName": ""
    }, {
      "mimeType": "application/applixware",
      "fileExtensions": ".aw",
      "friendlyName": ""
    }, {
      "mimeType": "application/atom+xml",
      "fileExtensions": ".atom",
      "friendlyName": ""
    }, {
      "mimeType": "application/atomcat+xml",
      "fileExtensions": ".atomcat",
      "friendlyName": ""
    }, {
      "mimeType": "application/atomsvc+xml",
      "fileExtensions": ".atomsvc",
      "friendlyName": ""
    }, {
      "mimeType": "application/ccxml+xml",
      "fileExtensions": ".ccxml",
      "friendlyName": ""
    }, {
      "mimeType": "application/cu-seeme",
      "fileExtensions": ".cu",
      "friendlyName": ""
    }, {
      "mimeType": "application/davmount+xml",
      "fileExtensions": ".davmount",
      "friendlyName": ""
    }, {
      "mimeType": "application/ecmascript",
      "fileExtensions": ".ecma",
      "friendlyName": ""
    }, {
      "mimeType": "application/emma+xml",
      "fileExtensions": ".emma",
      "friendlyName": ""
    }, {
      "mimeType": "application/epub+zip",
      "fileExtensions": ".epub",
      "friendlyName": ""
    }, {
      "mimeType": "application/font-tdpfr",
      "fileExtensions": ".pfr",
      "friendlyName": ""
    }, {
      "mimeType": "application/hyperstudio",
      "fileExtensions": ".stk",
      "friendlyName": ""
    }, {
      "mimeType": "application/java-archive",
      "fileExtensions": ".jar",
      "friendlyName": ""
    }, {
      "mimeType": "application/java-serialized-object",
      "fileExtensions": ".ser",
      "friendlyName": ""
    }, {
      "mimeType": "application/java-vm",
      "fileExtensions": ".class",
      "friendlyName": ""
    }, {
      "mimeType": "application/javascript",
      "fileExtensions": ".js",
      "friendlyName": ""
    }, {
      "mimeType": "application/json",
      "fileExtensions": ".json",
      "friendlyName": ""
    }, {
      "mimeType": "application/lost+xml",
      "fileExtensions": ".lostxml",
      "friendlyName": ""
    }, {
      "mimeType": "application/mac-binhex40",
      "fileExtensions": ".hqx",
      "friendlyName": ""
    }, {
      "mimeType": "application/mac-compactpro",
      "fileExtensions": ".cpt",
      "friendlyName": ""
    }, {
      "mimeType": "application/marc",
      "fileExtensions": ".mrc",
      "friendlyName": ""
    }, {
      "mimeType": "application/mathematica",
      "fileExtensions": ".ma,.nb,.mb",
      "friendlyName": ""
    }, {
      "mimeType": "application/mathml+xml",
      "fileExtensions": ".mathml",
      "friendlyName": ""
    }, {
      "mimeType": "application/mbox",
      "fileExtensions": ".mbox",
      "friendlyName": ""
    }, {
      "mimeType": "application/mediaservercontrol+xml",
      "fileExtensions": ".mscml",
      "friendlyName": ""
    }, {
      "mimeType": "application/mp4",
      "fileExtensions": ".mp4s",
      "friendlyName": ""
    }, {
      "mimeType": "application/msword",
      "fileExtensions": ".doc,.dot",
      "friendlyName": ""
    }, {
      "mimeType": "application/mxf",
      "fileExtensions": ".mxf",
      "friendlyName": ""
    }, {
      "mimeType": "application/oda",
      "fileExtensions": ".oda",
      "friendlyName": ""
    }, {
      "mimeType": "application/oebps-package+xml",
      "fileExtensions": ".opf",
      "friendlyName": ""
    }, {
      "mimeType": "application/octet-stream",
      "fileExtensions": ".?",
      "friendlyName": "Binary"
    }, {
      "mimeType": "application/ogg",
      "fileExtensions": ".ogx",
      "friendlyName": ""
    }, {
      "mimeType": "application/onenote",
      "fileExtensions": ".onetoc,.onetoc2,.onetmp,.onepkg",
      "friendlyName": ""
    }, {
      "mimeType": "application/patch-ops-error+xml",
      "fileExtensions": ".xer",
      "friendlyName": ""
    }, {
      "mimeType": "application/pdf",
      "fileExtensions": ".pdf",
      "friendlyName": ""
    }, {
      "mimeType": "application/pgp-encrypted",
      "fileExtensions": ".pgp",
      "friendlyName": ""
    }, {
      "mimeType": "application/pgp-signature",
      "fileExtensions": ".asc,.sig",
      "friendlyName": ""
    }, {
      "mimeType": "application/pics-rules",
      "fileExtensions": ".prf",
      "friendlyName": ""
    }, {
      "mimeType": "application/pkcs10",
      "fileExtensions": ".p10",
      "friendlyName": ""
    }, {
      "mimeType": "application/pkcs7-mime",
      "fileExtensions": ".p7m,.p7c",
      "friendlyName": ""
    }, {
      "mimeType": "application/pkcs7-signature",
      "fileExtensions": ".p7s",
      "friendlyName": ""
    }, {
      "mimeType": "application/pkix-cert",
      "fileExtensions": ".cer",
      "friendlyName": ""
    }, {
      "mimeType": "application/pkix-crl",
      "fileExtensions": ".crl",
      "friendlyName": ""
    }, {
      "mimeType": "application/pkix-pkifileExtension",
      "fileExtensions": ".pkifileExtension",
      "friendlyName": ""
    }, {
      "mimeType": "application/pkixcmp",
      "fileExtensions": ".pki",
      "friendlyName": ""
    }, {
      "mimeType": "application/pls+xml",
      "fileExtensions": ".pls",
      "friendlyName": ""
    }, {
      "mimeType": "application/postscript",
      "fileExtensions": ".ai,.eps,.ps",
      "friendlyName": ""
    }, {
      "mimeType": "application/prs.cww",
      "fileExtensions": ".cww",
      "friendlyName": ""
    }, {
      "mimeType": "application/rdf+xml",
      "fileExtensions": ".rdf",
      "friendlyName": ""
    }, {
      "mimeType": "application/reginfo+xml",
      "fileExtensions": ".rif",
      "friendlyName": ""
    }, {
      "mimeType": "application/relax-ng-compact-syntax",
      "fileExtensions": ".rnc",
      "friendlyName": ""
    }, {
      "mimeType": "application/resource-lists+xml",
      "fileExtensions": ".rl",
      "friendlyName": ""
    }, {
      "mimeType": "application/resource-lists-diff+xml",
      "fileExtensions": ".rld",
      "friendlyName": ""
    }, {
      "mimeType": "application/rls-services+xml",
      "fileExtensions": ".rs",
      "friendlyName": ""
    }, {
      "mimeType": "application/rsd+xml",
      "fileExtensions": ".rsd",
      "friendlyName": ""
    }, {
      "mimeType": "application/rss+xml",
      "fileExtensions": ".rss",
      "friendlyName": ""
    }, {
      "mimeType": "application/rtf",
      "fileExtensions": ".rtf",
      "friendlyName": ""
    }, {
      "mimeType": "application/sbml+xml",
      "fileExtensions": ".sbml",
      "friendlyName": ""
    }, {
      "mimeType": "application/scvp-cv-request",
      "fileExtensions": ".scq",
      "friendlyName": ""
    }, {
      "mimeType": "application/scvp-cv-response",
      "fileExtensions": ".scs",
      "friendlyName": ""
    }, {
      "mimeType": "application/scvp-vp-request",
      "fileExtensions": ".spq",
      "friendlyName": ""
    }, {
      "mimeType": "application/scvp-vp-response",
      "fileExtensions": ".spp",
      "friendlyName": ""
    }, {
      "mimeType": "application/sdp",
      "fileExtensions": ".sdp",
      "friendlyName": ""
    }, {
      "mimeType": "application/set-payment-initiation",
      "fileExtensions": ".setpay",
      "friendlyName": ""
    }, {
      "mimeType": "application/set-registration-initiation",
      "fileExtensions": ".setreg",
      "friendlyName": ""
    }, {
      "mimeType": "application/shf+xml",
      "fileExtensions": ".shf",
      "friendlyName": ""
    }, {
      "mimeType": "application/smil+xml",
      "fileExtensions": ".smi,.smil",
      "friendlyName": ""
    }, {
      "mimeType": "application/sparql-query",
      "fileExtensions": ".rq",
      "friendlyName": ""
    }, {
      "mimeType": "application/sparql-results+xml",
      "fileExtensions": ".srx",
      "friendlyName": ""
    }, {
      "mimeType": "application/srgs",
      "fileExtensions": ".gram",
      "friendlyName": ""
    }, {
      "mimeType": "application/srgs+xml",
      "fileExtensions": ".grxml",
      "friendlyName": ""
    }, {
      "mimeType": "application/ssml+xml",
      "fileExtensions": ".ssml",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.3gpp.pic-bw-large",
      "fileExtensions": ".plb",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.3gpp.pic-bw-small",
      "fileExtensions": ".psb",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.3gpp.pic-bw-var",
      "fileExtensions": ".pvb",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.3gpp2.tcap",
      "fileExtensions": ".tcap",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.3m.post-it-notes",
      "fileExtensions": ".pwn",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.accpac.simply.aso",
      "fileExtensions": ".aso",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.accpac.simply.imp",
      "fileExtensions": ".imp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.acucobol",
      "fileExtensions": ".acu",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.acucorp",
      "fileExtensions": ".atc,.acutc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.adobe.air-application-installer-package+zip",
      "fileExtensions": ".air",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.adobe.xdp+xml",
      "fileExtensions": ".xdp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.adobe.xfdf",
      "fileExtensions": ".xfdf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.airzip.filesecure.azf",
      "fileExtensions": ".azf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.airzip.filesecure.azs",
      "fileExtensions": ".azs",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.amazon.ebook",
      "fileExtensions": ".azw",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.americandynamics.acc",
      "fileExtensions": ".acc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.amiga.ami",
      "fileExtensions": ".ami",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.android.package-archive",
      "fileExtensions": ".apk",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.anser-web-certificate-issue-initiation",
      "fileExtensions": ".cii",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.anser-web-funds-transfer-initiation",
      "fileExtensions": ".fti",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.antix.game-component",
      "fileExtensions": ".atx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.apple.installer+xml",
      "fileExtensions": ".mpkg",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.arastra.swi",
      "fileExtensions": ".swi",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.audiograph",
      "fileExtensions": ".aep",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.blueice.multipass",
      "fileExtensions": ".mpm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.bmi",
      "fileExtensions": ".bmi",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.businessobjects",
      "fileExtensions": ".rep",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.chemdraw+xml",
      "fileExtensions": ".cdxml",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.chipnuts.karaoke-mmd",
      "fileExtensions": ".mmd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.cinderella",
      "fileExtensions": ".cdy",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.claymore",
      "fileExtensions": ".cla",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.clonk.c4group",
      "fileExtensions": ".c4g,.c4d,.c4f,.c4p,.c4u",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.commonspace",
      "fileExtensions": ".csp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.contact.cmsg",
      "fileExtensions": ".cdbcmsg",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.cosmocaller",
      "fileExtensions": ".cmc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.crick.clicker",
      "fileExtensions": ".clkx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.crick.clicker.keyboard",
      "fileExtensions": ".clkk",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.crick.clicker.palette",
      "fileExtensions": ".clkp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.crick.clicker.template",
      "fileExtensions": ".clkt",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.crick.clicker.wordbank",
      "fileExtensions": ".clkw",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.criticaltools.wbs+xml",
      "fileExtensions": ".wbs",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ctc-posml",
      "fileExtensions": ".pml",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.cups-ppd",
      "fileExtensions": ".ppd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.curl.car",
      "fileExtensions": ".car",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.curl.pcurl",
      "fileExtensions": ".pcurl",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.data-vision.rdz",
      "fileExtensions": ".rdz",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.denovo.fcselayout-link",
      "fileExtensions": ".fe_launch",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.dna",
      "fileExtensions": ".dna",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.dolby.mlp",
      "fileExtensions": ".mlp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.dpgraph",
      "fileExtensions": ".dpg",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.dreamfactory",
      "fileExtensions": ".dfac",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.dynageo",
      "fileExtensions": ".geo",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ecowin.chart",
      "fileExtensions": ".mag",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.enliven",
      "fileExtensions": ".nml",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.epson.esf",
      "fileExtensions": ".esf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.epson.msf",
      "fileExtensions": ".msf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.epson.quickanime",
      "fileExtensions": ".qam",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.epson.salt",
      "fileExtensions": ".slt",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.epson.ssf",
      "fileExtensions": ".ssf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.eszigno3+xml",
      "fileExtensions": ".es3,.et3",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ezpix-album",
      "fileExtensions": ".ez2",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ezpix-package",
      "fileExtensions": ".ez3",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.fdf",
      "fileExtensions": ".fdf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.fdsn.mseed",
      "fileExtensions": ".mseed",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.fdsn.seed",
      "fileExtensions": ".seed,.dataless",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.flographit",
      "fileExtensions": ".gph",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.fluxtime.clip",
      "fileExtensions": ".ftc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.framemaker",
      "fileExtensions": ".fm,.frame,.maker,.book",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.frogans.fnc",
      "fileExtensions": ".fnc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.frogans.ltf",
      "fileExtensions": ".ltf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.fsc.weblaunch",
      "fileExtensions": ".fsc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.fujitsu.oasys",
      "fileExtensions": ".oas",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.fujitsu.oasys2",
      "fileExtensions": ".oa2",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.fujitsu.oasys3",
      "fileExtensions": ".oa3",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.fujitsu.oasysgp",
      "fileExtensions": ".fg5",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.fujitsu.oasysprs",
      "fileExtensions": ".bh2",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.fujixerox.ddd",
      "fileExtensions": ".ddd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.fujixerox.docuworks",
      "fileExtensions": ".xdw",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.fujixerox.docuworks.binder",
      "fileExtensions": ".xbd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.fuzzysheet",
      "fileExtensions": ".fzs",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.genomatix.tuxedo",
      "fileExtensions": ".txd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.geogebra.file",
      "fileExtensions": ".ggb",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.geogebra.tool",
      "fileExtensions": ".ggt",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.geometry-explorer",
      "fileExtensions": ".gex,.gre",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.gmx",
      "fileExtensions": ".gmx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.google-apps.document",
      "fileExtensions": ".gdoc",
      "friendlyName": "Google Docs"
    }, {
      "mimeType": "application/vnd.google-apps.drawing",
      "fileExtensions": ".g?",
      "friendlyName": "Google Drawing"
    }, {
      "mimeType": "application/vnd.google-apps.file",
      "fileExtensions": ".g?",
      "friendlyName": "Google Drive file"
    }, {
      "mimeType": "application/vnd.google-apps.folder",
      "fileExtensions": ".g?",
      "friendlyName": "Google Drive folder"
    }, {
      "mimeType": "application/vnd.google-apps.form",
      "fileExtensions": ".g?",
      "friendlyName": "Google Forms"
    }, {
      "mimeType": "application/vnd.google-apps.fusiontable",
      "fileExtensions": ".g?",
      "friendlyName": "Google Fusion Tables"
    }, {
      "mimeType": "application/vnd.google-apps.presentation",
      "fileExtensions": ".gslides",
      "friendlyName": "Google Slides"
    }, {
      "mimeType": "application/vnd.google-apps.script",
      "fileExtensions": ".g?",
      "friendlyName": "Google Apps Scripts"
    }, {
      "mimeType": "application/vnd.google-apps.sites",
      "fileExtensions": ".g?",
      "friendlyName": "Google Sites"
    }, {
      "mimeType": "application/vnd.google-apps.spreadsheet",
      "fileExtensions": ".gsheet",
      "friendlyName": "Google Sheets"
    }, {
      "mimeType": "application/vnd.google-earth.kml+xml",
      "fileExtensions": ".kml",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.google-earth.kmz",
      "fileExtensions": ".kmz",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.grafeq",
      "fileExtensions": ".gqf,.gqs",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.groove-account",
      "fileExtensions": ".gac",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.groove-help",
      "fileExtensions": ".ghf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.groove-identity-message",
      "fileExtensions": ".gim",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.groove-injector",
      "fileExtensions": ".grv",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.groove-tool-message",
      "fileExtensions": ".gtm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.groove-tool-template",
      "fileExtensions": ".tpl",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.groove-vcard",
      "fileExtensions": ".vcg",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.handheld-entertainment+xml",
      "fileExtensions": ".zmm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.hbci",
      "fileExtensions": ".hbci",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.hhe.lesson-player",
      "fileExtensions": ".les",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.hp-hpgl",
      "fileExtensions": ".hpgl",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.hp-hpid",
      "fileExtensions": ".hpid",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.hp-hps",
      "fileExtensions": ".hps",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.hp-jlyt",
      "fileExtensions": ".jlt",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.hp-pcl",
      "fileExtensions": ".pcl",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.hp-pclxl",
      "fileExtensions": ".pclxl",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.hydrostatix.sof-data",
      "fileExtensions": ".sfd-hdstx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.hzn-3d-crossword",
      "fileExtensions": ".x3d",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ibm.minipay",
      "fileExtensions": ".mpy",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ibm.modcap",
      "fileExtensions": ".afp,.listafp,.list3820",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ibm.rights-management",
      "fileExtensions": ".irm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ibm.secure-container",
      "fileExtensions": ".sc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.iccprofile",
      "fileExtensions": ".icc,.icm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.igloader",
      "fileExtensions": ".igl",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.immervision-ivp",
      "fileExtensions": ".ivp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.immervision-ivu",
      "fileExtensions": ".ivu",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.intercon.formnet",
      "fileExtensions": ".xpw,.xpx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.intu.qbo",
      "fileExtensions": ".qbo",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.intu.qfx",
      "fileExtensions": ".qfx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ipunplugged.rcprofile",
      "fileExtensions": ".rcprofile",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.irepository.package+xml",
      "fileExtensions": ".irp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.is-xpr",
      "fileExtensions": ".xpr",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.jam",
      "fileExtensions": ".jam",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.jcp.javame.midlet-rms",
      "fileExtensions": ".rms",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.jisp",
      "fileExtensions": ".jisp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.joost.joda-archive",
      "fileExtensions": ".joda",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.kahootz",
      "fileExtensions": ".ktz,.ktr",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.kde.karbon",
      "fileExtensions": ".karbon",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.kde.kchart",
      "fileExtensions": ".chrt",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.kde.kformula",
      "fileExtensions": ".kfo",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.kde.kivio",
      "fileExtensions": ".flw",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.kde.kontour",
      "fileExtensions": ".kon",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.kde.kpresenter",
      "fileExtensions": ".kpr,.kpt",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.kde.kspread",
      "fileExtensions": ".ksp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.kde.kword",
      "fileExtensions": ".kwd,.kwt",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.kenameaapp",
      "fileExtensions": ".htke",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.kidspiration",
      "fileExtensions": ".kia",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.kinar",
      "fileExtensions": ".kne,.knp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.koan",
      "fileExtensions": ".skp,.skd,.skt,.skm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.kodak-descriptor",
      "fileExtensions": ".sse",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.llamagraphics.life-balance.desktop",
      "fileExtensions": ".lbd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.llamagraphics.life-balance.exchange+xml",
      "fileExtensions": ".lbe",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.lotus-1-2-3",
      "fileExtensions": ".123",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.lotus-approach",
      "fileExtensions": ".apr",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.lotus-freelance",
      "fileExtensions": ".pre",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.lotus-notes",
      "fileExtensions": ".nsf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.lotus-organizer",
      "fileExtensions": ".org",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.lotus-screencam",
      "fileExtensions": ".scm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.lotus-wordpro",
      "fileExtensions": ".lwp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.macports.portpkg",
      "fileExtensions": ".portpkg",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mcd",
      "fileExtensions": ".mcd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.medcalcdata",
      "fileExtensions": ".mc1",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mediastation.cdkey",
      "fileExtensions": ".cdkey",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mfer",
      "fileExtensions": ".mwf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mfmp",
      "fileExtensions": ".mfm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.micrografx.flo",
      "fileExtensions": ".flo",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.micrografx.igx",
      "fileExtensions": ".igx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mif",
      "fileExtensions": ".mif",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mobius.daf",
      "fileExtensions": ".daf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mobius.dis",
      "fileExtensions": ".dis",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mobius.mbk",
      "fileExtensions": ".mbk",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mobius.mqy",
      "fileExtensions": ".mqy",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mobius.msl",
      "fileExtensions": ".msl",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mobius.plc",
      "fileExtensions": ".plc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mobius.txf",
      "fileExtensions": ".txf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mophun.application",
      "fileExtensions": ".mpn",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mophun.certificate",
      "fileExtensions": ".mpc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mozilla.xul+xml",
      "fileExtensions": ".xul",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-artgalry",
      "fileExtensions": ".cil",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-cab-compressed",
      "fileExtensions": ".cab",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-excel",
      "fileExtensions": ".xls,.xlm,.xla,.xlc,.xlt,.xlw",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-excel.addin.macroenabled.12",
      "fileExtensions": ".xlam",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-excel.sheet.binary.macroenabled.12",
      "fileExtensions": ".xlsb",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-excel.sheet.macroenabled.12",
      "fileExtensions": ".xlsm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-excel.template.macroenabled.12",
      "fileExtensions": ".xltm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-fontobject",
      "fileExtensions": ".eot",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-htmlhelp",
      "fileExtensions": ".chm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-ims",
      "fileExtensions": ".ims",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-lrm",
      "fileExtensions": ".lrm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-pki.seccat",
      "fileExtensions": ".cat",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-pki.stl",
      "fileExtensions": ".stl",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-powerpoint",
      "fileExtensions": ".ppt,.pps,.pot",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-powerpoint.addin.macroenabled.12",
      "fileExtensions": ".ppam",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-powerpoint.presentation.macroenabled.12",
      "fileExtensions": ".pptm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-powerpoint.slide.macroenabled.12",
      "fileExtensions": ".sldm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-powerpoint.slideshow.macroenabled.12",
      "fileExtensions": ".ppsm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-powerpoint.template.macroenabled.12",
      "fileExtensions": ".potm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-project",
      "fileExtensions": ".mpp,.mpt",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-word.document.macroenabled.12",
      "fileExtensions": ".docm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-word.template.macroenabled.12",
      "fileExtensions": ".dotm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-works",
      "fileExtensions": ".wps,.wks,.wcm,.wdb",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-wpl",
      "fileExtensions": ".wpl",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ms-xpsdocument",
      "fileExtensions": ".xps",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.mseq",
      "fileExtensions": ".mseq",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.musician",
      "fileExtensions": ".mus",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.muvee.style",
      "fileExtensions": ".msty",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.neurolanguage.nlu",
      "fileExtensions": ".nlu",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.noblenet-directory",
      "fileExtensions": ".nnd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.noblenet-sealer",
      "fileExtensions": ".nns",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.noblenet-web",
      "fileExtensions": ".nnw",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.nokia.n-gage.data",
      "fileExtensions": ".ngdat",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.nokia.n-gage.symbian.install",
      "fileExtensions": ".n-gage",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.nokia.radio-preset",
      "fileExtensions": ".rpst",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.nokia.radio-presets",
      "fileExtensions": ".rpss",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.novadigm.edm",
      "fileExtensions": ".edm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.novadigm.edx",
      "fileExtensions": ".edx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.novadigm.ext",
      "fileExtensions": ".ext",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.chart",
      "fileExtensions": ".odc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.chart-template",
      "fileExtensions": ".otc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.database",
      "fileExtensions": ".odb",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.formula",
      "fileExtensions": ".odf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.formula-template",
      "fileExtensions": ".odft",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.graphics",
      "fileExtensions": ".odg",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.graphics-template",
      "fileExtensions": ".otg",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.image",
      "fileExtensions": ".odi",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.image-template",
      "fileExtensions": ".oti",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.presentation",
      "fileExtensions": ".odp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.spreadsheet",
      "fileExtensions": ".ods",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.spreadsheet-template",
      "fileExtensions": ".ots",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.text",
      "fileExtensions": ".odt",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.text-master",
      "fileExtensions": ".otm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.text-template",
      "fileExtensions": ".ott",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oasis.opendocument.text-web",
      "fileExtensions": ".oth",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.olpc-sugar",
      "fileExtensions": ".xo",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.oma.dd2+xml",
      "fileExtensions": ".dd2",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.openofficeorg.extension",
      "fileExtensions": ".oxt",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "fileExtensions": ".pptx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.openxmlformats-officedocument.presentationml.slide",
      "fileExtensions": ".sldx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
      "fileExtensions": ".ppsx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.openxmlformats-officedocument.presentationml.template",
      "fileExtensions": ".potx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "fileExtensions": ".xlsx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
      "fileExtensions": ".xltx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "fileExtensions": ".docx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
      "fileExtensions": ".dotx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.osgi.dp",
      "fileExtensions": ".dp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.palm",
      "fileExtensions": ".pdb,.pqa,.oprc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.pg.format",
      "fileExtensions": ".str",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.pg.osasli",
      "fileExtensions": ".ei6",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.picsel",
      "fileExtensions": ".efif",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.pocketlearn",
      "fileExtensions": ".plf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.powerbuilder6",
      "fileExtensions": ".pbd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.previewsystems.box",
      "fileExtensions": ".box",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.proteus.magazine",
      "fileExtensions": ".mgz",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.publishare-delta-tree",
      "fileExtensions": ".qps",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.pvi.ptid1",
      "fileExtensions": ".ptid",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.quark.quarkxpress",
      "fileExtensions": ".qxd,.qxt,.qwd,.qwt,.qxl,.qxb",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.recordare.musicxml",
      "fileExtensions": ".mxl",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.recordare.musicxml+xml",
      "fileExtensions": ".musicxml",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.rim.cod",
      "fileExtensions": ".cod",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.rn-realmedia",
      "fileExtensions": ".rm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.route66.link66+xml",
      "fileExtensions": ".link66",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.seemail",
      "fileExtensions": ".see",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.sema",
      "fileExtensions": ".sema",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.semd",
      "fileExtensions": ".semd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.semf",
      "fileExtensions": ".semf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.shana.informed.formdata",
      "fileExtensions": ".ifm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.shana.informed.formtemplate",
      "fileExtensions": ".itp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.shana.informed.interchange",
      "fileExtensions": ".iif",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.shana.informed.package",
      "fileExtensions": ".ipk",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.simtech-mindmapper",
      "fileExtensions": ".twd,.twds",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.smaf",
      "fileExtensions": ".mmf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.smart.teacher",
      "fileExtensions": ".teacher",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.solent.sdkm+xml",
      "fileExtensions": ".sdkm,.sdkd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.spotfire.dxp",
      "fileExtensions": ".dxp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.spotfire.sfs",
      "fileExtensions": ".sfs",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.stardivision.calc",
      "fileExtensions": ".sdc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.stardivision.draw",
      "fileExtensions": ".sda",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.stardivision.impress",
      "fileExtensions": ".sdd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.stardivision.math",
      "fileExtensions": ".smf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.stardivision.writer",
      "fileExtensions": ".sdw",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.stardivision.writer",
      "fileExtensions": ".vor",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.stardivision.writer-global",
      "fileExtensions": ".sgl",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.sun.xml.calc",
      "fileExtensions": ".sxc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.sun.xml.calc.template",
      "fileExtensions": ".stc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.sun.xml.draw",
      "fileExtensions": ".sxd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.sun.xml.draw.template",
      "fileExtensions": ".std",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.sun.xml.impress",
      "fileExtensions": ".sxi",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.sun.xml.impress.template",
      "fileExtensions": ".sti",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.sun.xml.math",
      "fileExtensions": ".sxm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.sun.xml.writer",
      "fileExtensions": ".sxw",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.sun.xml.writer.global",
      "fileExtensions": ".sxg",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.sun.xml.writer.template",
      "fileExtensions": ".stw",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.sus-calendar",
      "fileExtensions": ".sus,.susp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.svd",
      "fileExtensions": ".svd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.symbian.install",
      "fileExtensions": ".sis,.sisx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.syncml+xml",
      "fileExtensions": ".xsm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.syncml.dm+wbxml",
      "fileExtensions": ".bdm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.syncml.dm+xml",
      "fileExtensions": ".xdm",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.tao.intent-module-archive",
      "fileExtensions": ".tao",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.tmobile-livetv",
      "fileExtensions": ".tmo",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.trid.tpt",
      "fileExtensions": ".tpt",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.triscape.mxs",
      "fileExtensions": ".mxs",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.trueapp",
      "fileExtensions": ".tra",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.ufdl",
      "fileExtensions": ".ufd,.ufdl",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.uiq.theme",
      "fileExtensions": ".utz",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.umajin",
      "fileExtensions": ".umj",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.unity",
      "fileExtensions": ".unityweb",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.uoml+xml",
      "fileExtensions": ".uoml",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.vcx",
      "fileExtensions": ".vcx",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.visio",
      "fileExtensions": ".vsd,.vst,.vss,.vsw",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.visionary",
      "fileExtensions": ".vis",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.vsf",
      "fileExtensions": ".vsf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.wap.wbxml",
      "fileExtensions": ".wbxml",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.wap.wmlc",
      "fileExtensions": ".wmlc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.wap.wmlscriptc",
      "fileExtensions": ".wmlsc",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.webturbo",
      "fileExtensions": ".wtb",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.wordperfect",
      "fileExtensions": ".wpd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.wqd",
      "fileExtensions": ".wqd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.wt.stf",
      "fileExtensions": ".stf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.xara",
      "fileExtensions": ".xar",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.xfdl",
      "fileExtensions": ".xfdl",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.yamaha.hv-dic",
      "fileExtensions": ".hvd",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.yamaha.hv-script",
      "fileExtensions": ".hvs",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.yamaha.hv-voice",
      "fileExtensions": ".hvp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.yamaha.openscoreformat",
      "fileExtensions": ".osf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.yamaha.openscoreformat.osfpvg+xml",
      "fileExtensions": ".osfpvg",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.yamaha.smaf-audio",
      "fileExtensions": ".saf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.yamaha.smaf-phrase",
      "fileExtensions": ".spf",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.yellowriver-custom-menu",
      "fileExtensions": ".cmp",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.zul",
      "fileExtensions": ".zir,.zirz",
      "friendlyName": ""
    }, {
      "mimeType": "application/vnd.zzazz.deck+xml",
      "fileExtensions": ".zaz",
      "friendlyName": ""
    }, {
      "mimeType": "application/voicexml+xml",
      "fileExtensions": ".vxml",
      "friendlyName": ""
    }, {
      "mimeType": "application/winhlp",
      "fileExtensions": ".hlp",
      "friendlyName": ""
    }, {
      "mimeType": "application/wsdl+xml",
      "fileExtensions": ".wsdl",
      "friendlyName": ""
    }, {
      "mimeType": "application/wspolicy+xml",
      "fileExtensions": ".wspolicy",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-abiword",
      "fileExtensions": ".abw",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-ace-compressed",
      "fileExtensions": ".ace",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-authorware-bin",
      "fileExtensions": ".aab,.x32,.u32,.vox",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-authorware-map",
      "fileExtensions": ".aam",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-authorware-seg",
      "fileExtensions": ".aas",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-bcpio",
      "fileExtensions": ".bcpio",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-bittorrent",
      "fileExtensions": ".torrent",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-bzip",
      "fileExtensions": ".bz",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-bzip2",
      "fileExtensions": ".bz2,.boz",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-cdlink",
      "fileExtensions": ".vcd",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-chat",
      "fileExtensions": ".chat",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-chess-pgn",
      "fileExtensions": ".pgn",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-cpio",
      "fileExtensions": ".cpio",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-csh",
      "fileExtensions": ".csh",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-debian-package",
      "fileExtensions": ".deb,.udeb",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-director",
      "fileExtensions": ".dir,.dcr,.dxr,.cst,.cct,.cxt,.w3d,.fgd,.swa",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-doom",
      "fileExtensions": ".wad",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-dtbncx+xml",
      "fileExtensions": ".ncx",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-dtbook+xml",
      "fileExtensions": ".dtb",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-dtbresource+xml",
      "fileExtensions": ".res",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-dvi",
      "fileExtensions": ".dvi",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-font-bdf",
      "fileExtensions": ".bdf",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-font-ghostscript",
      "fileExtensions": ".gsf",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-font-linux-psf",
      "fileExtensions": ".psf",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-font-otf",
      "fileExtensions": ".otf",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-font-pcf",
      "fileExtensions": ".pcf",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-font-snf",
      "fileExtensions": ".snf",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-font-ttf",
      "fileExtensions": ".ttf,.ttc",
      "friendlyName": ""
    }, {
      "mimeType": "application/font-woff",
      "fileExtensions": ".woff",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-font-type1",
      "fileExtensions": ".pfa,.pfb,.pfm,.afm",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-futuresplash",
      "fileExtensions": ".spl",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-gnumeric",
      "fileExtensions": ".gnumeric",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-gtar",
      "fileExtensions": ".gtar",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-hdf",
      "fileExtensions": ".hdf",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-java-jnlp-file",
      "fileExtensions": ".jnlp",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-latex",
      "fileExtensions": ".latex",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-mobipocket-ebook",
      "fileExtensions": ".prc,.mobi",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-ms-application",
      "fileExtensions": ".application",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-ms-wmd",
      "fileExtensions": ".wmd",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-ms-wmz",
      "fileExtensions": ".wmz",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-ms-xbap",
      "fileExtensions": ".xbap",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-msaccess",
      "fileExtensions": ".mdb",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-msbinder",
      "fileExtensions": ".obd",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-mscardfile",
      "fileExtensions": ".crd",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-msclip",
      "fileExtensions": ".clp",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-msdownload",
      "fileExtensions": ".exe,.dll,.com,.bat,.msi",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-msmediaview",
      "fileExtensions": ".mvb,.m13,.m14",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-msmetafile",
      "fileExtensions": ".wmf",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-msmoney",
      "fileExtensions": ".mny",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-mspublisher",
      "fileExtensions": ".pub",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-msschedule",
      "fileExtensions": ".scd",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-msterminal",
      "fileExtensions": ".trm",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-mswrite",
      "fileExtensions": ".wri",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-netcdf",
      "fileExtensions": ".nc,.cdf",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-pkcs12",
      "fileExtensions": ".p12,.pfx",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-pkcs7-certificates",
      "fileExtensions": ".p7b,.spc",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-pkcs7-certreqresp",
      "fileExtensions": ".p7r",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-rar-compressed",
      "fileExtensions": ".rar",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-sh",
      "fileExtensions": ".sh",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-shar",
      "fileExtensions": ".shar",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-shockwave-flash",
      "fileExtensions": ".swf",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-silverlight-app",
      "fileExtensions": ".xap",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-stuffit",
      "fileExtensions": ".sit",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-stuffitx",
      "fileExtensions": ".sitx",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-sv4cpio",
      "fileExtensions": ".sv4cpio",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-sv4crc",
      "fileExtensions": ".sv4crc",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-tar",
      "fileExtensions": ".tar",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-tcl",
      "fileExtensions": ".tcl",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-tex",
      "fileExtensions": ".tex",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-tex-tfm",
      "fileExtensions": ".tfm",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-texinfo",
      "fileExtensions": ".texinfo,.texi",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-ustar",
      "fileExtensions": ".ustar",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-wais-source",
      "fileExtensions": ".src",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-x509-ca-cert",
      "fileExtensions": ".der,.crt",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-xfig",
      "fileExtensions": ".fig",
      "friendlyName": ""
    }, {
      "mimeType": "application/x-xpinstall",
      "fileExtensions": ".xpi",
      "friendlyName": ""
    }, {
      "mimeType": "application/xenc+xml",
      "fileExtensions": ".xenc",
      "friendlyName": ""
    }, {
      "mimeType": "application/xhtml+xml",
      "fileExtensions": ".xhtml,.xht",
      "friendlyName": ""
    }, {
      "mimeType": "application/xml",
      "fileExtensions": ".xml,.xsl",
      "friendlyName": ""
    }, {
      "mimeType": "application/xml-dtd",
      "fileExtensions": ".dtd",
      "friendlyName": ""
    }, {
      "mimeType": "application/xop+xml",
      "fileExtensions": ".xop",
      "friendlyName": ""
    }, {
      "mimeType": "application/xslt+xml",
      "fileExtensions": ".xslt",
      "friendlyName": ""
    }, {
      "mimeType": "application/xspf+xml",
      "fileExtensions": ".xspf",
      "friendlyName": ""
    }, {
      "mimeType": "application/xv+xml",
      "fileExtensions": ".mxml,.xhvml,.xvml,.xvm",
      "friendlyName": ""
    }, {
      "mimeType": "application/zip",
      "fileExtensions": ".zip",
      "friendlyName": ""
    }, {
      "mimeType": "audio/adpcm",
      "fileExtensions": ".adp",
      "friendlyName": ""
    }, {
      "mimeType": "audio/basic",
      "fileExtensions": ".au,.snd",
      "friendlyName": ""
    }, {
      "mimeType": "audio/midi",
      "fileExtensions": ".mid,.midi,.kar,.rmi",
      "friendlyName": ""
    }, {
      "mimeType": "audio/mp4",
      "fileExtensions": ".mp4a",
      "friendlyName": ""
    }, {
      "mimeType": "audio/mp4a-latm",
      "fileExtensions": ".m4a,.m4p",
      "friendlyName": ""
    }, {
      "mimeType": "audio/mpeg",
      "fileExtensions": ".mpga,.mp2,.mp2a,.mp3,.m2a,.m3a",
      "friendlyName": ""
    }, {
      "mimeType": "audio/ogg",
      "fileExtensions": ".oga,.ogg,.spx",
      "friendlyName": ""
    }, {
      "mimeType": "audio/vnd.digital-winds",
      "fileExtensions": ".eol",
      "friendlyName": ""
    }, {
      "mimeType": "audio/vnd.dts",
      "fileExtensions": ".dts",
      "friendlyName": ""
    }, {
      "mimeType": "audio/vnd.dts.hd",
      "fileExtensions": ".dtshd",
      "friendlyName": ""
    }, {
      "mimeType": "audio/vnd.lucent.voice",
      "fileExtensions": ".lvp",
      "friendlyName": ""
    }, {
      "mimeType": "audio/vnd.ms-playready.media.pya",
      "fileExtensions": ".pya",
      "friendlyName": ""
    }, {
      "mimeType": "audio/vnd.nuera.ecelp4800",
      "fileExtensions": ".ecelp4800",
      "friendlyName": ""
    }, {
      "mimeType": "audio/vnd.nuera.ecelp7470",
      "fileExtensions": ".ecelp7470",
      "friendlyName": ""
    }, {
      "mimeType": "audio/vnd.nuera.ecelp9600",
      "fileExtensions": ".ecelp9600",
      "friendlyName": ""
    }, {
      "mimeType": "audio/x-aac",
      "fileExtensions": ".aac",
      "friendlyName": ""
    }, {
      "mimeType": "audio/x-aiff",
      "fileExtensions": ".aif,.aiff,.aifc",
      "friendlyName": ""
    }, {
      "mimeType": "audio/x-mpegurl",
      "fileExtensions": ".m3u",
      "friendlyName": ""
    }, {
      "mimeType": "audio/x-ms-wax",
      "fileExtensions": ".wax",
      "friendlyName": ""
    }, {
      "mimeType": "audio/x-ms-wma",
      "fileExtensions": ".wma",
      "friendlyName": ""
    }, {
      "mimeType": "audio/x-pn-realaudio",
      "fileExtensions": ".ram,.ra",
      "friendlyName": ""
    }, {
      "mimeType": "audio/x-pn-realaudio-plugin",
      "fileExtensions": ".rmp",
      "friendlyName": ""
    }, {
      "mimeType": "audio/x-wav",
      "fileExtensions": ".wav",
      "friendlyName": ""
    }, {
      "mimeType": "chemical/x-cdx",
      "fileExtensions": ".cdx",
      "friendlyName": ""
    }, {
      "mimeType": "chemical/x-cif",
      "fileExtensions": ".cif",
      "friendlyName": ""
    }, {
      "mimeType": "chemical/x-cmdf",
      "fileExtensions": ".cmdf",
      "friendlyName": ""
    }, {
      "mimeType": "chemical/x-cml",
      "fileExtensions": ".cml",
      "friendlyName": ""
    }, {
      "mimeType": "chemical/x-csml",
      "fileExtensions": ".csml",
      "friendlyName": ""
    }, {
      "mimeType": "chemical/x-xyz",
      "fileExtensions": ".xyz",
      "friendlyName": ""
    }, {
      "mimeType": "image/bmp",
      "fileExtensions": ".bmp",
      "friendlyName": ""
    }, {
      "mimeType": "image/cgm",
      "fileExtensions": ".cgm",
      "friendlyName": ""
    }, {
      "mimeType": "image/g3fax",
      "fileExtensions": ".g3",
      "friendlyName": ""
    }, {
      "mimeType": "image/gif",
      "fileExtensions": ".gif",
      "friendlyName": ""
    }, {
      "mimeType": "image/ief",
      "fileExtensions": ".ief",
      "friendlyName": ""
    }, {
      "mimeType": "image/jp2",
      "fileExtensions": ".jp2",
      "friendlyName": ""
    }, {
      "mimeType": "image/jpeg",
      "fileExtensions": ".jpeg,.jpg,.jpe",
      "friendlyName": ""
    }, {
      "mimeType": "image/pict",
      "fileExtensions": ".pict,.pic,.pct",
      "friendlyName": ""
    }, {
      "mimeType": "image/png",
      "fileExtensions": ".png",
      "friendlyName": ""
    }, {
      "mimeType": "image/prs.btif",
      "fileExtensions": ".btif",
      "friendlyName": ""
    }, {
      "mimeType": "image/svg+xml",
      "fileExtensions": ".svg,.svgz",
      "friendlyName": ""
    }, {
      "mimeType": "image/tiff",
      "fileExtensions": ".tiff,.tif",
      "friendlyName": ""
    }, {
      "mimeType": "image/vnd.adobe.photoshop",
      "fileExtensions": ".psd",
      "friendlyName": ""
    }, {
      "mimeType": "image/vnd.djvu",
      "fileExtensions": ".djvu,.djv",
      "friendlyName": ""
    }, {
      "mimeType": "image/vnd.dwg",
      "fileExtensions": ".dwg",
      "friendlyName": ""
    }, {
      "mimeType": "image/vnd.dxf",
      "fileExtensions": ".dxf",
      "friendlyName": ""
    }, {
      "mimeType": "image/vnd.fastbidsheet",
      "fileExtensions": ".fbs",
      "friendlyName": ""
    }, {
      "mimeType": "image/vnd.fpx",
      "fileExtensions": ".fpx",
      "friendlyName": ""
    }, {
      "mimeType": "image/vnd.fst",
      "fileExtensions": ".fst",
      "friendlyName": ""
    }, {
      "mimeType": "image/vnd.fujixerox.edmics-mmr",
      "fileExtensions": ".mmr",
      "friendlyName": ""
    }, {
      "mimeType": "image/vnd.fujixerox.edmics-rlc",
      "fileExtensions": ".rlc",
      "friendlyName": ""
    }, {
      "mimeType": "image/vnd.ms-modi",
      "fileExtensions": ".mdi",
      "friendlyName": ""
    }, {
      "mimeType": "image/vnd.net-fpx",
      "fileExtensions": ".npx",
      "friendlyName": ""
    }, {
      "mimeType": "image/vnd.wap.wbmp",
      "fileExtensions": ".wbmp",
      "friendlyName": ""
    }, {
      "mimeType": "image/vnd.xiff",
      "fileExtensions": ".xif",
      "friendlyName": ""
    }, {
      "mimeType": "image/x-cmu-raster",
      "fileExtensions": ".ras",
      "friendlyName": ""
    }, {
      "mimeType": "image/x-cmx",
      "fileExtensions": ".cmx",
      "friendlyName": ""
    }, {
      "mimeType": "image/x-freehand",
      "fileExtensions": ".fh,.fhc,.fh4,.fh5,.fh7",
      "friendlyName": ""
    }, {
      "mimeType": "image/x-icon",
      "fileExtensions": ".ico",
      "friendlyName": ""
    }, {
      "mimeType": "image/x-macpaint",
      "fileExtensions": ".pntg,.pnt,.mac",
      "friendlyName": ""
    }, {
      "mimeType": "image/x-pcx",
      "fileExtensions": ".pcx",
      "friendlyName": ""
    }, {
      "mimeType": "image/x-portable-anymap",
      "fileExtensions": ".pnm",
      "friendlyName": ""
    }, {
      "mimeType": "image/x-portable-bitmap",
      "fileExtensions": ".pbm",
      "friendlyName": ""
    }, {
      "mimeType": "image/x-portable-graymap",
      "fileExtensions": ".pgm",
      "friendlyName": ""
    }, {
      "mimeType": "image/x-portable-pixmap",
      "fileExtensions": ".ppm",
      "friendlyName": ""
    }, {
      "mimeType": "image/x-quicktime",
      "fileExtensions": ".qtif,.qti",
      "friendlyName": ""
    }, {
      "mimeType": "image/x-rgb",
      "fileExtensions": ".rgb",
      "friendlyName": ""
    }, {
      "mimeType": "image/x-xbitmap",
      "fileExtensions": ".xbm",
      "friendlyName": ""
    }, {
      "mimeType": "image/x-xpixmap",
      "fileExtensions": ".xpm",
      "friendlyName": ""
    }, {
      "mimeType": "image/x-xwindowdump",
      "fileExtensions": ".xwd",
      "friendlyName": ""
    }, {
      "mimeType": "message/rfc822",
      "fileExtensions": ".eml,.mime",
      "friendlyName": ""
    }, {
      "mimeType": "model/iges",
      "fileExtensions": ".igs,.iges",
      "friendlyName": ""
    }, {
      "mimeType": "model/mesh",
      "fileExtensions": ".msh,.mesh,.silo",
      "friendlyName": ""
    }, {
      "mimeType": "model/vnd.dwf",
      "fileExtensions": ".dwf",
      "friendlyName": ""
    }, {
      "mimeType": "model/vnd.gdl",
      "fileExtensions": ".gdl",
      "friendlyName": ""
    }, {
      "mimeType": "model/vnd.gtw",
      "fileExtensions": ".gtw",
      "friendlyName": ""
    }, {
      "mimeType": "model/vnd.mts",
      "fileExtensions": ".mts",
      "friendlyName": ""
    }, {
      "mimeType": "model/vnd.vtu",
      "fileExtensions": ".vtu",
      "friendlyName": ""
    }, {
      "mimeType": "model/vrml",
      "fileExtensions": ".wrl,.vrml",
      "friendlyName": ""
    }, {
      "mimeType": "text/calendar",
      "fileExtensions": ".ics,.ifb",
      "friendlyName": ""
    }, {
      "mimeType": "text/css",
      "fileExtensions": ".css",
      "friendlyName": ""
    }, {
      "mimeType": "text/csv",
      "fileExtensions": ".csv",
      "friendlyName": ""
    }, {
      "mimeType": "text/html",
      "fileExtensions": ".html,.htm",
      "friendlyName": ""
    }, {
      "mimeType": "text/plain",
      "fileExtensions": ".txt,.text,.conf,.def,.list,.log,.in",
      "friendlyName": ""
    }, {
      "mimeType": "text/prs.lines.tag",
      "fileExtensions": ".dsc",
      "friendlyName": ""
    }, {
      "mimeType": "text/richtext",
      "fileExtensions": ".rtx",
      "friendlyName": ""
    }, {
      "mimeType": "text/sgml",
      "fileExtensions": ".sgml,.sgm",
      "friendlyName": ""
    }, {
      "mimeType": "text/tab-separated-values",
      "fileExtensions": ".tsv",
      "friendlyName": ""
    }, {
      "mimeType": "text/troff",
      "fileExtensions": ".t,.tr,.roff,.man,.me,.ms",
      "friendlyName": ""
    }, {
      "mimeType": "text/uri-list",
      "fileExtensions": ".uri,.uris,.urls",
      "friendlyName": ""
    }, {
      "mimeType": "text/vnd.curl",
      "fileExtensions": ".curl",
      "friendlyName": ""
    }, {
      "mimeType": "text/vnd.curl.dcurl",
      "fileExtensions": ".dcurl",
      "friendlyName": ""
    }, {
      "mimeType": "text/vnd.curl.scurl",
      "fileExtensions": ".scurl",
      "friendlyName": ""
    }, {
      "mimeType": "text/vnd.curl.mcurl",
      "fileExtensions": ".mcurl",
      "friendlyName": ""
    }, {
      "mimeType": "text/vnd.fly",
      "fileExtensions": ".fly",
      "friendlyName": ""
    }, {
      "mimeType": "text/vnd.fmi.flexstor",
      "fileExtensions": ".flx",
      "friendlyName": ""
    }, {
      "mimeType": "text/vnd.graphviz",
      "fileExtensions": ".gv",
      "friendlyName": ""
    }, {
      "mimeType": "text/vnd.in3d.3dml",
      "fileExtensions": ".3dml",
      "friendlyName": ""
    }, {
      "mimeType": "text/vnd.in3d.spot",
      "fileExtensions": ".spot",
      "friendlyName": ""
    }, {
      "mimeType": "text/vnd.sun.j2me.app-descriptor",
      "fileExtensions": ".jad",
      "friendlyName": ""
    }, {
      "mimeType": "text/vnd.wap.wml",
      "fileExtensions": ".wml",
      "friendlyName": ""
    }, {
      "mimeType": "text/vnd.wap.wmlscript",
      "fileExtensions": ".wmls",
      "friendlyName": ""
    }, {
      "mimeType": "text/x-asm",
      "fileExtensions": ".s,.asm",
      "friendlyName": ""
    }, {
      "mimeType": "text/x-c",
      "fileExtensions": ".c,.cc,.cxx,.cpp,.h,.hh,.dic",
      "friendlyName": ""
    }, {
      "mimeType": "text/x-fortran",
      "fileExtensions": ".f,.for,.f77,.f90",
      "friendlyName": ""
    }, {
      "mimeType": "text/x-pascal",
      "fileExtensions": ".p,.pas",
      "friendlyName": ""
    }, {
      "mimeType": "text/x-java-source",
      "fileExtensions": ".java",
      "friendlyName": ""
    }, {
      "mimeType": "text/x-setext",
      "fileExtensions": ".etx",
      "friendlyName": ""
    }, {
      "mimeType": "text/x-uuencode",
      "fileExtensions": ".uu",
      "friendlyName": ""
    }, {
      "mimeType": "text/x-vcalendar",
      "fileExtensions": ".vcs",
      "friendlyName": ""
    }, {
      "mimeType": "text/x-vcard",
      "fileExtensions": ".vcf",
      "friendlyName": ""
    }, {
      "mimeType": "video/3gpp",
      "fileExtensions": ".3gp",
      "friendlyName": ""
    }, {
      "mimeType": "video/3gpp2",
      "fileExtensions": ".3g2",
      "friendlyName": ""
    }, {
      "mimeType": "video/h261",
      "fileExtensions": ".h261",
      "friendlyName": ""
    }, {
      "mimeType": "video/h263",
      "fileExtensions": ".h263",
      "friendlyName": ""
    }, {
      "mimeType": "video/h264",
      "fileExtensions": ".h264",
      "friendlyName": ""
    }, {
      "mimeType": "video/jpeg",
      "fileExtensions": ".jpgv",
      "friendlyName": ""
    }, {
      "mimeType": "video/jpm",
      "fileExtensions": ".jpm,.jpgm",
      "friendlyName": ""
    }, {
      "mimeType": "video/mj2",
      "fileExtensions": ".mj2,.mjp2",
      "friendlyName": ""
    }, {
      "mimeType": "video/mp4",
      "fileExtensions": ".mp4,.mp4v,.mpg4,.m4v",
      "friendlyName": ""
    }, {
      "mimeType": "video/webm",
      "fileExtensions": ".webm",
      "friendlyName": ""
    }, {
      "mimeType": "video/mpeg",
      "fileExtensions": ".mpeg,.mpg,.mpe,.m1v,.m2v",
      "friendlyName": ""
    }, {
      "mimeType": "video/ogg",
      "fileExtensions": ".ogv",
      "friendlyName": ""
    }, {
      "mimeType": "video/quicktime",
      "fileExtensions": ".qt,.mov",
      "friendlyName": ""
    }, {
      "mimeType": "video/vnd.fvt",
      "fileExtensions": ".fvt",
      "friendlyName": ""
    }, {
      "mimeType": "video/vnd.mpegurl",
      "fileExtensions": ".mxu,.m4u",
      "friendlyName": ""
    }, {
      "mimeType": "video/vnd.ms-playready.media.pyv",
      "fileExtensions": ".pyv",
      "friendlyName": ""
    }, {
      "mimeType": "video/vnd.vivo",
      "fileExtensions": ".viv",
      "friendlyName": ""
    }, {
      "mimeType": "video/x-dv",
      "fileExtensions": ".dv,.dif",
      "friendlyName": ""
    }, {
      "mimeType": "video/x-f4v",
      "fileExtensions": ".f4v",
      "friendlyName": ""
    }, {
      "mimeType": "video/x-fli",
      "fileExtensions": ".fli",
      "friendlyName": ""
    }, {
      "mimeType": "video/x-flv",
      "fileExtensions": ".flv",
      "friendlyName": ""
    }, {
      "mimeType": "video/x-ms-asf",
      "fileExtensions": ".asf,.asx",
      "friendlyName": ""
    }, {
      "mimeType": "video/x-ms-wm",
      "fileExtensions": ".wm",
      "friendlyName": ""
    }, {
      "mimeType": "video/x-ms-wmv",
      "fileExtensions": ".wmv",
      "friendlyName": ""
    }, {
      "mimeType": "video/x-ms-wmx",
      "fileExtensions": ".wmx",
      "friendlyName": ""
    }, {
      "mimeType": "video/x-ms-wvx",
      "fileExtensions": ".wvx",
      "friendlyName": ""
    }, {
      "mimeType": "video/x-msvideo",
      "fileExtensions": ".avi",
      "friendlyName": ""
    }, {
      "mimeType": "video/x-sgi-movie",
      "fileExtensions": ".movie",
      "friendlyName": ""
    }, {
      "mimeType": "x-conference/x-cooltalk",
      "fileExtensions": ".ice",
      "friendlyName": ""
    }
  ]
}